// Les secrets sont configurés uniquement dans Cloudflare, jamais dans ce dépôt.
const enc=new TextEncoder();
const fail=(message,status=400)=>Object.assign(new Error(message),{status});
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store'}});
const b64url=buf=>btoa(String.fromCharCode(...new Uint8Array(buf))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
const unbase=s=>Uint8Array.from(atob(s.replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0));
async function key(secret){return crypto.subtle.importKey('raw',enc.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign','verify']);}
async function sign(payload,secret){return b64url(await crypto.subtle.sign('HMAC',await key(secret),enc.encode(payload)));}
export async function authorized(request,env){try{const raw=request.headers.get('Authorization')||'';if(!raw.startsWith('Bearer '))return false;const [payload,sig,extra]=raw.slice(7).split('.');if(extra||!payload||!sig)return false;if(!await crypto.subtle.verify('HMAC',await key(env.SESSION_SECRET),unbase(sig),enc.encode(payload)))return false;const d=JSON.parse(new TextDecoder().decode(unbase(payload)));return Number.isFinite(d.expires)&&d.expires>Date.now()&&d.expires<=Date.now()+1800000;}catch{return false;}}
export function validateRecord(r){if(!r||typeof r!=='object')throw fail('Fiche invalide.');const str=(v,max,required=false)=>{if(typeof v!=='string'||v.length>max||(required&&!v.trim()))throw fail('Un champ est manquant ou trop long.');return v.trim();};const id=str(r.id,80,true);if(!/^[a-zA-Z0-9-]{1,80}$/.test(id))throw fail('Identifiant invalide.');if(!['collection','recherche'].includes(r.statut))throw fail('Classement invalide.');if(!Array.isArray(r.disques)||r.disques.length>20)throw fail('20 disques maximum.');return {id,artiste:str(r.artiste,120,true),album:str(r.album,160,true),statut:r.statut,notes:str(r.notes||'',2000),disques:r.disques.map((d,i)=>{if(!Array.isArray(d.titres)||d.titres.length>100)throw fail('100 morceaux maximum par disque.');return {numero:i+1,titres:d.titres.map(t=>{const duree=str(t.duree||'',7);if(duree&&!/^\d{1,3}:[0-5]\d$/.test(duree))throw fail('Durée invalide : utilise 3:42.');return {face:str(t.face||'',2),titre:str(t.titre,200,true),duree};})};})};}
export default {async fetch(request,env){const origin=request.headers.get('Origin');if(origin!==env.ALLOWED_ORIGIN)return json({error:'Origine non autorisée.'},403);const headers={'Access-Control-Allow-Origin':env.ALLOWED_ORIGIN,'Access-Control-Allow-Methods':'GET, POST, DELETE, OPTIONS','Access-Control-Allow-Headers':'Content-Type, Authorization','Vary':'Origin'};if(request.method==='OPTIONS')return new Response(null,{status:204,headers});const issues=[];if(!env.GITHUB_TOKEN)issues.push('GITHUB_TOKEN absent');if(!env.ADMIN_PIN)issues.push('ADMIN_PIN absent');else if(!/^\d{6,12}$/.test(env.ADMIN_PIN))issues.push('ADMIN_PIN doit contenir 6 à 12 chiffres sans espaces');if(!env.SESSION_SECRET)issues.push('SESSION_SECRET absent');else if(env.SESSION_SECRET.length<32)issues.push('SESSION_SECRET doit contenir au moins 32 caractères');if(issues.length)return new Response(JSON.stringify({error:'Configuration à corriger : '+issues.join(' ; ')}),{status:503,headers:{...headers,'Content-Type':'application/json','Cache-Control':'no-store'}});const id=env.COLLECTION.idFromName('collection');const response=await env.COLLECTION.get(id).fetch(request);const result=new Response(response.body,response);Object.entries(headers).forEach(([k,v])=>result.headers.set(k,v));return result;}};
export class Collection {
 constructor(ctx,env){this.ctx=ctx;this.env=env;this.queue=Promise.resolve();}
 fetch(request){const job=this.queue.then(()=>this.handle(request));this.queue=job.catch(()=>{});return job;}
 async gh(path,body,method=body?'POST':'GET'){const r=await fetch(`https://api.github.com/repos/${this.env.GITHUB_REPO}/${path}`,{method,headers:{Authorization:`Bearer ${this.env.GITHUB_TOKEN}`,'User-Agent':'LaFaceVM','Accept':'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28',...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});if(!r.ok){if(r.status===409||r.status===422)throw fail('La collection a changé. Actualise la page avant de réessayer.',409);throw fail('GitHub est indisponible ou son autorisation a expiré. Réessaie plus tard.',502);}return r.json();}
 async catalogue(){const ref=await this.gh('git/ref/heads/main'),head=ref.object.sha;const commit=await this.gh('git/commits/'+head);const file=await this.gh('contents/docs/data/index.json?ref='+head);const decoded=new TextDecoder().decode(unbase(file.content.replace(/\s/g,'')));return {head,tree:commit.tree.sha,records:JSON.parse(decoded).records};}
 async body(request){if(Number(request.headers.get('Content-Length'))>1200000)throw fail('Envoi trop volumineux.',413);const reader=request.body?.getReader();if(!reader)throw fail('Requête vide.');let total=0,chunks=[];while(true){const {done,value}=await reader.read();if(done)break;total+=value.length;if(total>1200000){await reader.cancel();throw fail('Envoi trop volumineux.',413);}chunks.push(value);}const bytes=new Uint8Array(total);let pos=0;chunks.forEach(c=>{bytes.set(c,pos);pos+=c.length;});try{return JSON.parse(new TextDecoder().decode(bytes));}catch{throw fail('Requête invalide.');}}
 async handle(request){try{const path=new URL(request.url).pathname;
 if(path==='/login'&&request.method==='POST'){
 const now=Date.now(),attempts=await this.ctx.storage.get('attempts')||{count:0,until:0};if(attempts.until>now&&attempts.count>=5)throw fail('Trop de tentatives. Réessaie dans 15 minutes.',429);
 const data=await this.body(request);const candidate=typeof data.pin==='string'?data.pin:'';const a=new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(candidate))),b=new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(this.env.ADMIN_PIN)));let diff=0;for(let i=0;i<a.length;i++)diff|=a[i]^b[i];
 if(diff){const count=attempts.until>now?attempts.count+1:1;await this.ctx.storage.put('attempts',{count,until:count>=5?now+900000:attempts.until>now?attempts.until:now+900000});throw fail('Code PIN incorrect.',401);}await this.ctx.storage.delete('attempts');const expires=now+1800000,payload=b64url(enc.encode(JSON.stringify({expires,nonce:crypto.randomUUID()})));return json({token:payload+'.'+await sign(payload,this.env.SESSION_SECRET),expires});}
 if(path!=='/records')throw fail('Page introuvable.',404);
 if(request.method==='GET'){const cached=this.cache;if(cached&&Date.now()-cached.at<10000)return json({records:cached.records});const c=await this.catalogue();this.cache={records:c.records,at:Date.now()};return json({records:c.records});}
 if(!['POST','DELETE'].includes(request.method))throw fail('Méthode non autorisée.',405);
 if(!await authorized(request,this.env))throw fail('Déverrouille les modifications pour continuer.',401);
 const body=await this.body(request),c=await this.catalogue(),entries=[];
 if(request.method==='DELETE'){const old=c.records.find(r=>r.id===body.id);if(!old)throw fail('Vinyle introuvable.',404);if(old.version!==body.version)throw fail('Cette fiche a changé. Actualise la collection.',409);c.records=c.records.filter(r=>r.id!==old.id);entries.push({path:`docs/data/vinyles/${old.id}.json`,mode:'100644',type:'blob',sha:null});if(old.image)entries.push({path:'docs/'+old.image,mode:'100644',type:'blob',sha:null});}
 else {const r=validateRecord(body.record),old=c.records.find(x=>x.id===r.id);if((old?.version||null)!==(body.record.version||null))throw fail('Cette fiche a changé. Actualise la collection.',409);r.version=crypto.randomUUID();r.image=old?.image||'';
 if(body.image!==undefined){if(typeof body.image!=='string'||body.image.length>1000000||!/^\/9j\/[A-Za-z0-9+/]*={0,2}$/.test(body.image))throw fail('Pochette JPEG invalide ou trop lourde.');const blob=await this.gh('git/blobs',{content:body.image,encoding:'base64'});r.image=`images/${r.id}-${r.version}.jpg`;entries.push({path:'docs/'+r.image,mode:'100644',type:'blob',sha:blob.sha});if(old?.image)entries.push({path:'docs/'+old.image,mode:'100644',type:'blob',sha:null});}
 c.records=c.records.filter(x=>x.id!==r.id);c.records.push(r);entries.push({path:`docs/data/vinyles/${r.id}.json`,mode:'100644',type:'blob',content:JSON.stringify(r,null,2)+'\n'});}
 entries.push({path:'docs/data/index.json',mode:'100644',type:'blob',content:JSON.stringify({records:c.records},null,2)+'\n'});
 const tree=await this.gh('git/trees',{base_tree:c.tree,tree:entries}),commit=await this.gh('git/commits',{message:request.method==='DELETE'?'Supprimer un vinyle':'Enregistrer un vinyle',tree:tree.sha,parents:[c.head]});await this.gh('git/refs/heads/main',{sha:commit.sha,force:false},'PATCH');this.cache={records:c.records,at:Date.now()};return json({records:c.records});
 }catch(e){return json({error:e.status?e.message:'Le service rencontre un problème. Réessaie plus tard.'},e.status||500);}}
}
